### ISSUE TITLE
Server starts and can be found via IP but connecting not possible

### ISSUE THREAD

**Issue by Pixelplanet** [mattieserver/docker-csgo-server#1]
so i managed to get the server running but i run into the problem that the server can be found when i enter the IP but the game will not allow connecting, any idea what could be going on here?

**Comment by mattieserver** [comment]
can you paste your docker run command?

**Comment by Pixelplanet** [comment]
im using the docker wizard build into my Synology NAS so i dont really have a Docker run command.

i started the server with stock settings before and left it like it is since doing my tests.
for some reason i can now connect to it without any problem, no idea what was going on before.

now i just gotta figure out how to configure this server correctly and check if the performance is good enough.
